name: Deployment pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: Check style
        run: |
          npm run eslint
      - name: Building application
        run: |
          npm run build 
      - name: Testing application 
        run: |
          npm run test
      - name: Bump version and push tag
        uses: anorthrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}